name: Green Local Sleeve
favicon: null
layout_spectrum: 0.96638
typography_spectrum: 0.35531
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#bdbdab'
    - '#1a1a1a'
    - '#676663'
    - '#8c8c7e'
  brandStrength: 0.3125
  lightness: 0.375
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
