name: Green Local Sleeve
favicon: null
layout_spectrum: 0.048533106688410044
typography_spectrum: 0.8622129673603922
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9553190008737147
  lightness: 0.5653338201809675
  saturation: 0.41127114929258823
  rhythmicContrast: 0.29693357553333044
purpose: []
